### ISSUE TITLE
February 2020 has 29 days.

### ISSUE THREAD

**Issue by patel999jay** [meta4/mplcal#3] opened 2021-02-05 04:55 UTC
It looks like `February 2020` it generates `29` days somehow.

![image](https://user-images.githubusercontent.com/5512610/106991583-ec9fc080-674c-11eb-87ec-077919ab0622.png)

**Comment by meta4** [comment] 2021-02-05 06:50
Hi Jay,

Thanks for your interest in mplcal.

The best I can tell is mplcal is working as intended.  What were you expecting to see?

2020 was a [leap year][1], so February 2020 should have 29 days.  [Here is a link][2] to the February 2020 calendar from timeanddate.com. It looks the same as your example.

I use the python built-in [calendar module][3] for the date calculations.  So, if the issue is a local issue we will have to look into that library.

[1]: https://en.wikipedia.org/wiki/Leap_year
[2]: https://www.timeanddate.com/calendar/monthly.html?year=2020&month=2&country=1 
[3]: https://docs.python.org/3/library/calendar.html

**Comment by meta4** [comment] 2021-03-28 23:22
No follow-up for 2 months.

The issue may have been posted in error.

Closing this issue.

**Closed as completed by meta4** 2021-03-28 23:22 UTC
Labels: question
